"""next meeting date added

Revision ID: f9d233664ce8
Revises: d57649d77e60
Create Date: 2023-06-19 16:40:03.458027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9d233664ce8'
down_revision = 'd57649d77e60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_clubs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('next_meeting_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_clubs', schema=None) as batch_op:
        batch_op.drop_column('next_meeting_date')

    # ### end Alembic commands ###
