"""Added Books table

Revision ID: 74092c6a48a4
Revises: a924485a36cf
Create Date: 2023-06-19 15:15:52.024682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74092c6a48a4'
down_revision = 'a924485a36cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('cover_image', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('book_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books')
    # ### end Alembic commands ###
