"""Book - book club relationship

Revision ID: d57649d77e60
Revises: 74092c6a48a4
Create Date: 2023-06-19 15:17:41.244240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd57649d77e60'
down_revision = '74092c6a48a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_clubs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('book_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_book_clubs_book_id_books'), 'books', ['book_id'], ['book_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_clubs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_book_clubs_book_id_books'), type_='foreignkey')
        batch_op.drop_column('book_id')

    # ### end Alembic commands ###
